language: python
dist: xenial

python:
  - "3.6"

cache:
  directories:
      - "~/.platformio"

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-avr binutils-avr avr-libc python3-pip python3-wheel
  - pip3 install  setuptools
  - pip3 install  platformio
  - platformio update
    # - pip3 install --user cpp-coveralls

jobs:
  include:
    # - stage: "Linux target"
    #   name: "Linux target"
    #   compiler: gcc
    #   script:
    #     - pio run
    #     - cd build_linux 
    #     - cmake  ../ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=TRUE
    #     - cmake --build . && ctest
    #   after_success:
    #     - coveralls --exclude CMakeFiles/ --gcov-options '\-lp'
    - stage: "AVR target"
      name: "AVR target"
      compiler: avr-gcc
      script:
        - pio run -v -d .
