#!/bin/bash
PIO_HOME="${PIO_HOME:-${HOME}/.platformio}"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"

"${PIO_HOME}/packages/tool-avrdude/avrdude" \
    -v  \
    -B8 \
    -pt84 \
    -cdragon_isp \
    -b115200  \
    -C "${PIO_HOME}/packages/tool-avrdude/avrdude.conf" \
    -Uflash:w:"${PROJECT_DIR}/.pio/build/$1/firmware.hex" \
    -U efuse:w:0xff:m  \
    -U hfuse:w:0xdf:m  \
    -U lfuse:w:0x62:m
